### ISSUE TITLE
Problems installing version 1.0.1

### ISSUE THREAD

**Issue by a-shkarupin** [wanzysky/smart_path#3]
Tried to install recently published version 1.0.1 and got the following issue:
```
Collecting smart_path==1.0.1
  Using cached smart_path-1.0.1.tar.gz (3.4 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/alsh/.virtualenvs/test/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_1heppee/smart-path_74bfd6d137dd420ba4c6af79a62febb2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_1heppee/smart-path_74bfd6d137dd420ba4c6af79a62febb2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-a_dmpy9n
         cwd: /tmp/pip-install-_1heppee/smart-path_74bfd6d137dd420ba4c6af79a62febb2/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_1heppee/smart-path_74bfd6d137dd420ba4c6af79a62febb2/setup.py", line 12, in <module>
        with open("requirements.txt") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
I believe there was no issue with version 1.0.0 because the wheel was used for install, however for 1.0.1 wheel distro is not available, instead there's an egg: https://pypi.org/project/smart-path/1.0.1/#files.
When trying to install from tar.gz distro, getting same error for version 1.0.0.

**Comment by wanzysky** [comment]
Sorry, I forgot to upload the whl file, which has been uploaded now.
